controllers/BlogController.php
<?php
/**
 * Created by PhpStorm.
 * User: xenia
 * Date: 03.05.17
 * Time: 14:06
 */

namespace app\controllers;

use app\models\BlogPost;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;


class BlogController extends Controller
{
    public function actionIndex()
    {
        $provider = new ActiveDataProvider([
           'query' => BlogPost::find(),
           'pagination' => [
                'pageSize' => 20,
                ],
        ]);

        return $this->render('index', ['dataProvider' => $provider]);

    }

    public function actionUpdate($id = null)
    {
        if ($id !== null) {
            $model = BlogPost::findOne($id);
        } else {
            $model = new BlogPost();
        }
        if ($model->load(\Yii::$app->request->post())) {
            if ($model->validate()) {
                $model->save();
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', ['model' => $model]);
    }

    public function actionDelete($id)
    {
        $post = BlogPost::findOne($id);
        $post->delete();

       return $this->redirect(['index']);
    }

}

controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: xenia
 * Date: 05.05.17
 * Time: 12:54
 */

namespace app\controllers;
use app\models\Login;
use Yii;
use app\models\Reg;
use yii\web\Controller;


class UserController extends Controller
{
    public function actionReg()
    {
        $model = new Reg();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->reg()) {
                // if (Yii::$app->getUser()->login($user)) {
                return $this->goHome();
            }
        }
        // }

        return $this->render('reg', [
            'model' => $model,
        ]);
    }

    public function actionLogin()
    {
        $model = new Login();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->login()) {
                return '1';

            }

        }
        return $this->render('login', [
            'model' => $model,
        ]);

    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ['label' => 'Registration', 'url' => ['/user/reg']],
            ['label' => 'Login2', 'url' => ['/user/login']],
            ['label' => 'Articles', 'url' => ['/blog/index']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/user/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/user/logout'], 'post')
                . Html::submitButton(
                    'Выйти (' . Yii::$app->user->identity->userName . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>